### ISSUE TITLE
Missing "OEIntellivisionSystemResponderClient.h"

### ISSUE THREAD

**Issue by toxikman** [OpenEmu/Bliss-Core#1]
Tried building so I could add this plugin to OpenEmu, but it didn't work. Sorry I'm kind of doing this blindly, but here's the error I got:

BlissGameCore.mm:31:9: 'OEIntellivisionSystemResponderClient.h' file not found

**Comment by clobber** [comment]
You would need to do a recursive init on the submodules when you clone to get everything. Building from source right now isn't a good idea because the frontend is broken and undergoing a redesign and cores kind of require the new frontend as well. Anyway, next release will have this system/core included and that should be soon enough.

**Comment by toxikman** [comment]
ok, I'll wait, thanks!
